pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://artifacts-cn-beijing.volces.com/repository/picoxrtob' }
    }
}

rootProject.name = "STYLY-MDM Client"
include ':app'
